export const APPWRITE_VARIABLES = {
  PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID || "",
  DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID || "",
  TABLE_ID: process.env.EXPO_PUBLIC_APPWRITE_TABLE_ID || "",
  MAIN_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT || "",
};
